# Generated by Django 4.2.19 on 2025-02-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rooms',
            new_name='Room',
        ),
    ]
